name: todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  gradient_app_bar:
    git:
      url: https://github.com/TinyProgrammers/GradientAppBar.git
  sqflite:
  path_provider:
  path:
  flutter_datetime_picker: ^1.2.1
  intl: ^0.15.8
  flutter_local_notifications:
  timezone:
  location:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
  test: any
  mockito:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
